---
- name: Install pre reqs
  ansible.builtin.apt:
    pkg:
    - gnupg
    - software-properties-common
    state: present
    update_cache: yes

- name: Add hashicorp apt repository key.
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: '0644'
    force: true

- name: Add hashicorp apt repository
  apt_repository: 
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb['codename'] }} main"
    filename: "hashicorp"
    state: present
    update_cache: yes

- name: Install terraform 
  apt: 
    name: terraform
    update_cache: yes