- name: Add hashicorp apt repository key.
  ansible.builtin.get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: /etc/apt/trusted.gpg.d/hashicorp.asc
    mode: '0644'

- name: Add hashicorp apt repository
  apt_repository: 
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_lsb['codename'] }} main"
    filename: "hashicorp"
    state: present
    update_cache: yes

- name: Install packer 
  apt: 
    name: packer
    update_cache: yes