- name: Setup devops box
  hosts: all

  roles:
    - azure-cli
    - standard-packages
    - packer
    - terraform
    - pwsh
    - pwsh_modules
    - pip
    - ansible_pip
    - kubectl
